matriz = [
    [["Hemoglobina", " Hb :", "g/dL"], 10, "Hemoglobina", 10],
    [["CONTAGEM DE PLAQUETAS", " Plqt: ", "/mm³"], 45, "Resultado", 14],
    [["Leucócitos", " Leuco: ", "/mm³"], 12, "Leucócitos", 12],
    [["UREIA", " U: ", "mg/dL"], 87, "Resultado", 12],
    [["CREATININA", " Cr: ", "mg/dL"], 60, "Resultado", 10],
    [["CK-MB  MASSA", " CK-MB: ", "ng/mL"], 53, "Resultado", 10],
    [["TROPONINA I", " Tropo: ", "ng/L"], 68, "Resultado", 10],
    [["CREATINOFOSFOQUINASE", " CPK: ", "U/L"], 36, "Resultado", 10],
    [["TGO", " TGO: ", "U/L"], 68,"Resultado", 10],
    [["TGP", " TGP: ", "U/L"], 84, "Resultado", 10],
    [["GAMA GLUTAMIL", " Gama-GT: ","U/L" ], 53, "Resultado", 10],
    [["FOSFATASE ALCALINA", " FA: ", "U/L"], 33, "Resultado", 10],
    [["BILIRRUBINAS", " BT: ", "mg/dL"], 41, "Total",10 ],
    [["Direta", " BD: ", "md/dL"], 11, "Direta", 10],
    [["Indireta", " BI: ", "mg/dL"], 11, "Indireta", 10],
    [["FOSFORO", " P: ", "mg/dL"], 48, "Resultado", 10],
    [["MAGNESIO", " Mg: ", "mg/dL"], 54, "Resultado", 10],
    [["ALBUMINA", " Alb. : ", "g/dL"], 37, "Resultado", 10],
    [["AMILASE", " Amilase: ", "U/L"], 40, "Resultado", 10],
    [["LIPASE", " Lipase: ", "U/L"], 48, "Resultado", 10],
    [["DEHIDROGENASE", " DHL: ", "U/L"], 48, "Resultado", 12],
    [["VANCOMICINA", " Vanco: ", "µg/mL"], 80, "Resultado (*)", 10],
    [["GASOMETRIA ARTERIAL", " Gaso A: pH: ", ""], 200, "pH", 5],
    [["GASOMETRIA ARTERIAL", " pCO2: ", "mmHg"], 200, "pCO2", 8],
    [["GASOMETRIA ARTERIAL", " pO2: ", "mmHg"], 200, "pO2", 10],
    [["GASOMETRIA ARTERIAL", " SatO2: ", "%"], 200, "Saturação O2", 6],
    [["GASOMETRIA ARTERIAL", " HCO3: ", "mmol/L"], 200, "Bicarbonato", 6],
    [["GASOMETRIA ARTERIAL", " BE: ", "mmol/L"], 250, "BE", 6],
    [["GASOMETRIA VENOSA", " Gaso V: pH: ", ""], 200, "pH", 5],
    [["GASOMETRIA VENOSA", " pCO2: ", "mmHg"], 200, "pCO2", 8],
    [["GASOMETRIA VENOSA", " pO2: ", "mmHg"], 200, "pO2", 10],
    [["GASOMETRIA VENOSA", " SVcO2: ", "%"], 200, "Saturação O2", 6],
    [["GASOMETRIA VENOSA", " HCO3: ", "mmol/L"], 200, "Bicarbonato", 6],
    [["GASOMETRIA VENOSA", " BE: ", "mmol/L"], 250, "BE", 6],
    [["HEMOGLOBINA", " Hb: ", "g/dL"], 10, "Resultado", 10],
    [["HEMATOCRITO", " Ht: ", "%"], 10, "Resultado", 10],
    [["SODIO", " Na: ", "mEq/L"], 50, "Resultado", 8],
    [["POTASSIO", " K: ", "mEq/L"], 50, "Resultado", 8],
    [["CALCIO IONIZADO", " CaI: ", "mMol/L"], 50, "Resultado", 8],
    [["CLORO", " Cl: ", "mEq/L"], 50, "Resultado", 8],
    [["GLICOSE", " Glic.: ", "mg/dL"], 100, "Resultado", 8],
    [["COAGULOGRAMA", " INR: ", ""], 250, "INR", 5],
    [["COAGULOGRAMA", " R: ", ""], 250, "Relação Paciente/Normal", 5],
    [["FIBRINOGENIO", " Fib: ", "mg/dL"], 50, "Resultado", 8],
    [["LACTATO VENOSO", " Lact. V: ", "mg/dL"], 50, "Resultado", 8],
    [["LACTATO ARTERIAL", " Lact. A: ", "mg/dL"], 50, "Resultado", 8],
    [["COLESTEROL", " Col: ", "mg/dL"], 50, "Resultado", 8],
    [["HDL - COLESTEROL", " HDL: ", "mg/dL"], 50, "Resultado", 8],
    [["LDL - COLESTEROL", " LDL: ", "mg/dL"], 200, "Resultado", 12],
    [["NÃO HDL - COLESTEROL", " Não-HDL: ", "mg/dL"], 200, "Resultado", 8],
    [["HORMONIO TIREOESTIMULANTE", " TSH: ", "µUI/mL"], 50, "Resultado", 8],
    [["HEMOGLOBINA GLICADA", " Hb1AC: ", "%"], 200, "Resultado", 10],
    [["PROTEINA C REATIVA", " PCR: ", "mg/L"], 50, "Resultado", 8]
    
    



    
]