name = "extractor"
account_id = "972c925f8cde11ae41c11ed830943ab8"
workers_dev = true
route = { pattern = "", zone_id = ""}
main = "dist/main.js"
compatibility_date = "2022-06-03"

[build]
command = "npm run build"